### ISSUE TITLE
Port the to Linux

### ISSUE THREAD

**Issue by AndreMiras** [jeremyklelifa/Jukebar#1]
When trying to run on Linux (Gentoo), here's what I get:

```
$ python main_gui.py 
[INFO              ] [Logger      ] Record log in /home/andre/.kivy/logs/kivy_16-09-15_3.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.10 (default, Dec 11 2015, 23:50:31) 
[GCC 4.8.3]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "main_gui.py", line 15, in <module>
     from jukebar import run_jukebar
   File "/home/andre/Progz/GitHub/jeremyklelifa/Jukebar/Jukebar/jukebar.py", line 14, in <module>
     from pycaw.pycaw import AudioUtilities
   File "/home/andre/Progz/GitHub/jeremyklelifa/Jukebar/venv/lib/python2.7/site-packages/pycaw/pycaw.py", line 5, in <module>
     import comtypes
   File "/home/andre/Progz/GitHub/jeremyklelifa/Jukebar/venv/lib/python2.7/site-packages/comtypes/__init__.py", line 23, in <module>
     from _ctypes import COMError
 ImportError: cannot import name COMError
$
```

This is because the pycaw module is made for Windows.
We need to replace it with something similar on Linux.

**Comment by jeremyklelifa** [comment]
Merged PR#3
